---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: fluxcd-migration
    commit:
      author:
        name: fluxcdbot
        email: 47521326+nicolasvedrenne@users.noreply.github.com
      messageTemplate: |
        chore(images): update infrastructure images
    push:
      branch: fluxcd-migration
  update:
    path: ./infrastructure
    strategy: Setters
  policySelector:
    matchLabels:
      kube-minimal-stack.dev/automation: infrastructure
