apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ferriskey
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/ferriskey/charts
    chart: ferriskey
    targetRevision: v0.3.0
    helm:
      releaseName: ferriskey
      valuesObject:
        database:
          passwordSecret:
            annotations:
              argocd.argoproj.io/hook: PreSync
              argocd.argoproj.io/sync-wave: "0"
        databaseMigrations:
          annotations:
            argocd.argoproj.io/hook: PreSync
            argocd.argoproj.io/sync-wave: "1"
        postgresql:
          annotations:
            argocd.argoproj.io/hook: PreSync
            argocd.argoproj.io/sync-wave: "0"
          serviceAccount:
            annotations:
              argocd.argoproj.io/hook: PreSync
              argocd.argoproj.io/sync-wave: "0"
        ingress:
          enabled: false
          host: ferriskey.cluster.t1.intranet.campuscyber-na.fr
  destination:
    server: https://kubernetes.default.svc
    namespace: ferriskey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  revisionHistoryLimit: 10
