apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: quay.io/jetstack/charts
    chart: cert-manager
    targetRevision: v1.19.4
    helm:
      releaseName: cert-manager
      parameters:
        - name: crds.enabled
          value: "true"
        - name: config.apiVersion
          value: "controller.config.cert-manager.io/v1alpha1"
        - name: config.kind
          value: "ControllerConfiguration"
        - name: config.enableGatewayAPI
          value: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  revisionHistoryLimit: 10
