apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://your-custom-server/directory
    caBundle: "..."
    privateKeySecretRef:
      name: my-issuer-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: public-gateway
                namespace: gateway-system
                kind: Gateway
